version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: dennis4057/devops-qr-code-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile
    image: dennis4057/devops-qr-code-frontend:latest
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production

networks:
  default:
    driver: bridge
    


